import function_parameter_called_from_other_module
import function_parameter_called_from_other_module_distraction

function_parameter_called_from_other_module.f(42)
function_parameter_called_from_other_module.distraction({})
function_parameter_called_from_other_module_distraction.f([])

